# Generated by Django 5.0.7 on 2024-07-28 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('price_per_sqm', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('type_of_property', models.CharField(max_length=30)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_integration.tableinfo')),
            ],
        ),
    ]
