# Generated by Django 5.0.7 on 2024-07-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.FloatField(null=True)),
                ('avg_price_per_sqm', models.FloatField(null=True)),
                ('avg_sq_meter', models.FloatField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('min_price_per_sqm', models.FloatField(null=True)),
                ('min_sq_meter', models.FloatField(null=True)),
                ('max_price', models.FloatField(null=True)),
                ('max_price_per_sqm', models.FloatField(null=True)),
                ('max_sq_meter', models.FloatField(null=True)),
                ('median_price', models.FloatField(null=True)),
                ('median_price_per_sqm', models.FloatField(null=True)),
                ('median_sq_meter', models.FloatField(null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_integration.tableinfo')),
            ],
        ),
    ]
